import LegalLayout from '../components/LegalLayout'

function LegalDisclaimer() {
    return (
        <LegalLayout
            title="Legal Disclaimer"
            subtitle="Please read before relying on information provided by CCSP."
            lastUpdated="June 28, 2026"
        >
            <h2>Guidance Only</h2>
            <p>
                The Civic Candidate Support Platform provides organizational tools, educational resources, workflow
                assistance, reminders, and informational guidance designed to help users understand campaign administration.
            </p>
            <p>
                The platform does not replace official election authorities, campaign finance agencies, licensed attorneys,
                accountants, or other qualified professionals.
            </p>

            <h2>No Legal Advice</h2>
            <p>
                Information generated by CCSP, including information produced by the AI Compliance Assistant, is provided for
                informational purposes only.
            </p>
            <p>
                It should not be interpreted as legal advice, financial advice, accounting advice, or an official
                interpretation of campaign finance laws.
            </p>
            <p>
                Users remain responsible for ensuring compliance with all applicable federal, state, and local laws.
            </p>

            <h2>Official Sources</h2>
            <p>Whenever legal requirements apply, users should consult:</p>
            <ul>
                <li>official election authorities</li>
                <li>campaign finance agencies</li>
                <li>applicable statutes</li>
                <li>qualified legal counsel when necessary</li>
            </ul>

            <h2>AI Assistant Notice</h2>
            <p>
                The AI Compliance Assistant is intended to simplify complex information and explain compliance concepts in plain
                language.
            </p>
            <p>
                AI-generated responses may occasionally be incomplete or inaccurate.
            </p>
            <p>
                Users should verify important legal or regulatory matters using official sources before taking action.
            </p>

            <h2>User Responsibility</h2>
            <p>
                Submitting campaign filings, financial reports, disclosures, or other official documents remains the sole
                responsibility of the campaign and its authorized representatives.
            </p>

            <h2>Contact</h2>
            <p>
                Questions about this disclaimer can be sent to{' '}
                <a href="mailto:ccspcivicos@gmail.com">ccspcivicos@gmail.com</a>.
            </p>
        </LegalLayout>
    )
}

export default LegalDisclaimer
